//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CommonModeNoiseRejection.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COMMONMODENOISEREJECTION_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDB_PNG_DOWN_Y                  138
#define IDB_PNG_DOWN_Z                  139
#define IDB_PNG_LEFT_X                  140
#define IDB_PNG_RIGHT_X                 141
#define IDB_PNG_UP_X                    142
#define IDB_PNG_UP_Y                    142
#define IDB_PNG_UP_Z                    143
#define IDB_PNG_HOME                    144
#define IDD_ERROR_TYPE_SEL_DIALOG       145
#define IDB_PNG1                        148
#define IDB_PNG_S_0                     148
#define IDR_TOOLBAR_Settings            152
#define IDB_PNG_LINEAR                  154
#define IDB_PNG3                        155
#define IDB_PNG_FUN_GEN                 155
#define IDD_DIALOG_POINT_CANVAS         156
#define IDC_BTN_CONN                    1000
#define IDC_BTN_LEFT_X                  1001
#define IDC_BTN_RIGHT_X                 1002
#define IDC_BTN_DOWN_Y                  1003
#define IDC_BTN_UP_Y                    1004
#define IDC_BTN_UP_Z                    1005
#define IDC_BTN_DOWN_Z                  1006
#define IDC_COMBO_WAVEFORM              1007
#define IDC_EDIT_MAX_FREQ               1008
#define IDC_EDIT_MIN_FREQ               1009
#define IDC_EDIT_INC_FREQ               1011
#define IDC_EDIT_MAX_AMP                1013
#define IDC_EDIT_MIN_AMP                1014
#define IDC_EDIT_STEP_AMP               1015
#define IDC_EDIT_IMP                    1016
#define IDC_BTN_CMNR_START              1017
#define IDC_EDIT_ROUND_CNT              1018
#define IDC_EDIT_DUTY                   1020
#define IDC_SLIDER_DUTY                 1021
#define IDC_STATIC_MSG                  1022
#define IDC_PROG_FG                     1023
#define IDC_STATIC_DUTY                 1024
#define IDC_EDIT_POS_X                  1026
#define IDC_EDIT_POS_Y                  1027
#define IDC_EDIT_SAFE_HIGH              1028
#define IDC_EDIT_TOUCH_HIGH             1029
#define IDC_EDIT_STOP_TIME              1030
#define IDC_CHECK_NO_TOUCH              1031
#define IDC_BTN_HOME                    1032
#define IDC_LIST_RESULT                 1035
#define IDC_CHECK_MORE_TOUCH            1037
#define IDC_CHECK_PEN_UP                1038
#define IDC_CHECK_JITTER                1039
#define IDC_EDIT_JITTER_VALUE           1040
#define IDC_BTN_ERROR_TYPE_SEL          1041
#define IDC_BUTTON1                     1042
#define IDC_BUTTON_SHOW_POINT           1042
#define IDC_BUTTON_DRAW                 1043
#define IDC_BUTTON_LOAD_POINT_FILE      1044
#define IDC_LIST_PATH_TYPE              1045
#define IDC_MFCBUTTON_SHOWPATH          1046
#define IDC_MFCBUTTON_RUN               1047
#define IDC_COMBO_LAPS                  1049
#define IDC_STATIC_CHOOSE_LAPS          1050
#define IDC_PROGRESS1                   1051
#define IDC_PROGRESS_LINEAR_PROGRESS_BAR 1051
#define IDC_COMBO_LAPS2                 1052
#define IDC_COMBO_TP_TYPE               1052
#define IDC_STATIC_CHOOSE_TP_TYPE       1053
#define IDC_EDIT_TP_WIDTH               1054
#define IDC_EDIT2                       1055
#define IDC_EDIT_TP_HEIGHT              1055
#define IDC_EDIT_WIDTH                  1055
#define IDC_EDIT1                       1056
#define IDC_EDIT_RANGE                  1056
#define IDC_EDIT_HEIGHT                 1056
#define IDC_STATIC_TAG                  1057
#define IDC_SLIDER1                     1058
#define IDC_SLIDER_SPEED                1058
#define IDC_STATIC_RANGE                1059
#define IDC_STATIC_MIN                  1061
#define IDC_STATIC_MAX                  1062
#define IDC_STATIC_PULSE                1063
#define IDC_EDIT_START                  1064
#define IDC_COMBO1                      1065
#define IDC_COMBO_SELECT                1065
#define IDC_COMBO_SECTION               1065
#define IDC_RADIO_NORMAL_CMNR_TEST      1066
#define IDC_RADIO_1000_RANDOM           1067
#define IDC_RADIO_1000_ACCURATE         1068
#define IDC_EDIT_START2                 1068
#define IDC_EDIT_EDGE                   1068
#define IDC_STATIC_TEST_GROUP           1069
#define IDC_STATIC_POINT_RESTART        1070
#define IDC_CHECK1                      1071
#define IDC_CHECK_ACCURATE              1071
#define IDC_CHECKSHOW_NG                1071
#define IDC_CHECK_SHOW_NG               1071
#define IDC_CHECK_DEBUG                 1072
#define IDC_CHECK_SHOW_PASS             1072
#define IDC_BUTTON2                     1073
#define IDC_BUTTON_PNG                  1073
#define IDC_EDIT_LOGIC_PULSE_X          1074
#define IDC_EDIT_OFFSET_Y               1074
#define IDC_BUTTON4                     1075
#define IDC_EDIT_LOGIC_PULSE_Y          1076
#define IDC_EDIT_OFFSET_X               1076
#define IDC_EDIT_ACT_PULSE_Y            1077
#define IDC_EDIT_OFFSET_Y2              1077
#define IDC_EDIT_INNER_SIZE             1077
#define IDC_BUTTON3                     1078
#define IDC_EDIT_X0                     1079
#define IDC_EDIT_Y0                     1080
#define IDC_STATIC_PT0                  1081
#define IDC_STATIC_PT1                  1082
#define IDC_STATIC_PASS                 1082
#define IDC_EDIT_X1                     1083
#define IDC_STATIC_NG                   1083
#define IDC_EDIT_Y1                     1084
#define IDC_STATIC_PT2                  1085
#define IDC_EDIT_X2                     1086
#define IDC_EDIT_Y2                     1087
#define IDC_STATIC_PT3                  1088
#define IDC_EDIT_X3                     1089
#define IDC_EDIT_Y3                     1090
#define IDC_STATIC_PT4                  1091
#define IDC_EDIT_X4                     1092
#define IDC_EDIT_Y4                     1093
#define IDC_STATIC_EDGE                 1094
#define IDC_EDIT_PASS                   1095
#define IDC_BUTTON5                     1095
#define IDC_EDIT_NG                     1096
#define IDC_STATIC_INNER_SIZE           1096
#define IDC_EDIT_CNTX                   1097
#define IDC_EDIT_CNTY                   1098
#define IDC_EDIT_RESX                   1099
#define IDC_EDIT_RESY                   1100
#define IDC_COMBO2                      1101
#define IDC_COMBO_COORD_ZERO            1101
#define IDC_LINEAR_MACHINE              32771
#define IDC_TOOLBTN_SET_LINEAR_TEST     32774
#define IDC_TOOLBTN_SET_FUNCTIONGEN     32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
