#ifndef ___HFST_HID_SDK_ERRORCODEDEF_H__
#define ___HFST_HID_SDK_ERRORCODEDEF_H__

// Attention : the maximum error number must less 0xFF
#define HFST_HID_ERROR_OK									0
#define HFST_HID_ERROR_PARAM								( HFST_HID_ERROR_OK									+ 1 )	// invalid input param
#define HFST_HID_ERROR_ALLOC_MEMMORY						( HFST_HID_ERROR_PARAM								+ 1 )
#define HFST_HID_ERROR_DEVICE_NOT_FOUND						( HFST_HID_ERROR_ALLOC_MEMMORY						+ 1 )
#define HFST_HID_ERROR_GETDEVICE_COLLECTION					( HFST_HID_ERROR_DEVICE_NOT_FOUND					+ 1 )	// SetupDiGetClassDevs
#define HFST_HID_ERROR_GETDEVICE_INFORMATION				( HFST_HID_ERROR_GETDEVICE_COLLECTION				+ 1 )	// SetupDiEnumDeviceInterfaces fail
#define HFST_HID_ERROR_GETDEVICE_INFORMATION_DETAIL_SIZE	( HFST_HID_ERROR_GETDEVICE_INFORMATION				+ 1 )
#define HFST_HID_ERROR_GETDEVICE_INFORMATION_DETAIL_MSG		( HFST_HID_ERROR_GETDEVICE_INFORMATION_DETAIL_SIZE	+ 1 )
#define HFST_HID_ERROR_OPEN_DEVICE_NO_ACCESS				( HFST_HID_ERROR_GETDEVICE_INFORMATION_DETAIL_MSG	+ 1 )	// CreateFile
#define HFST_HID_ERROR_OPEN_DEVICE_ACCESS					( HFST_HID_ERROR_OPEN_DEVICE_NO_ACCESS				+ 1 )	// CreateFile
#define HFST_HID_ERROR_GETDEVICE_ATTRIBUTE					( HFST_HID_ERROR_OPEN_DEVICE_ACCESS					+ 1 )	// HidD_GetAttributes
#define HFST_HID_ERROR_GETDEVICE_PREPASED_DATA				( HFST_HID_ERROR_GETDEVICE_ATTRIBUTE				+ 1 )	// HidD_GetPreparsedData
#define HFST_HID_ERROR_GETDEVICE_CAPS						( HFST_HID_ERROR_GETDEVICE_PREPASED_DATA			+ 1 )	// HidP_GetCaps
#define HFST_HID_ERROR_GET_INPUT_REPORT						( HFST_HID_ERROR_GETDEVICE_CAPS						+ 1 )	// HidD_GetInputReport
#define HFST_HID_ERROR_GET_INPUT_REPORT_DATA_SIZE			( HFST_HID_ERROR_GET_INPUT_REPORT					+ 1 )
#define HFST_HID_ERROR_SET_OUTPUT_REPORT					( HFST_HID_ERROR_GET_INPUT_REPORT_DATA_SIZE			+ 1 )
#define HFST_HID_ERROR_SET_OUTPUT_REPORT_DATA_SIZE			( HFST_HID_ERROR_SET_OUTPUT_REPORT					+ 1 )
#define HFST_HID_ERROR_DESCRIBE_REPORT_LENGTH				( HFST_HID_ERROR_SET_OUTPUT_REPORT_DATA_SIZE		+ 1 )
#define HFST_HID_ERROR_DEVICE_PAGE							( HFST_HID_ERROR_DESCRIBE_REPORT_LENGTH				+ 1 )

#endif // ___HFST_HID_SDK_ERRORCODEDEF_H__
