//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CMNR.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_BUILD_TAB                   101
#define IDS_FIND_TAB                    102
#define IDS_DEBUG_TAB                   103
#define IDS_PROGRESS                    104
#define IDS_PROGRESS_LABEL              105
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CMNRTYPE                    130
#define IDR_TEST_VIEW_TOOL_BAR          134
#define ID_VIEW_OUTPUTWND               149
#define IDR_OUTPUT_POPUP                182
#define IDS_EDIT_MENU                   306
#define IDR_TOOLBAR_IC                  310
#define IDR_TOOLBAR_TEST                312
#define IDD_DIALOG_IC_VIEW              314
#define IDD_DIALOG_MACHINE_VIEW         316
#define IDR_XLISTBOX                    318
#define IDB_PNG_BACK                    320
#define IDB_PNG_DOWN                    321
#define IDB_PNG_FRONT                   322
#define IDB_PNG_LEFT                    323
#define IDB_PNG_RIGHT                   324
#define IDB_PNG_UP                      325
#define IDB_PNG1                        326
#define IDB_PNG_CENTER                  326
#define IDB_BITMAP_TREE_VIEW            327
#define IDB_PNG_IC_CONNECT              329
#define IDB_PNG_IC_DISCONNECT           330
#define IDB_PNG4                        331
#define IDB_PNG_IC_BOOTCODE             331
#define IDD_DIALOG_SETTING              332
#define IDB_PNG2                        336
#define IDB_PNG_IC_INFO_MORE            336
#define IDB_PNG3                        337
#define IDB_PNG_IC_INFO_FOLD            337
#define IDR_MENU1                       338
#define IDR_CONTEXTMENU                 338
#define IDB_PNG5                        341
#define IDB_PNG_CONNECT                 341
#define IDB_PNG6                        342
#define IDB_PNG_DISCONNECT              342
#define IDB_PNG7                        343
#define IDB_PNG_FOLD                    343
#define IDI_ICONCONNECT                 350
#define IDI_ICON_CONNECT                350
#define IDI_ICON_DISCONNECT             351
#define IDI_ICON_GREEN                  352
#define IDI_ICON4                       353
#define IDI_ICON_RED                    353
#define IDI_ICON5                       354
#define IDI_ICON_YELLOW                 354
#define IDB_BITMAP_CONNECT              357
#define IDB_BITMAP_DIS_CONNECT          358
#define IDB_BITMAP_DIS_CONNECT1         359
#define IDB_BITMAP_ISP                  359
#define IDB_BITMAP_CONNECT64            360
#define IDB_BITMAP1                     361
#define IDB_BITMAP_TEST_LIST            361
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_EDIT1                       1001
#define IDC_EDIT_IC_I2C_CLOCK           1001
#define IDC_BUTTON3                     1002
#define IDC_COMBO1                      1002
#define IDC_COMBO_IC_I2C_ADDR           1002
#define IDC_BUTTON_VIEW_LEFT            1003
#define IDC_COMBO2                      1003
#define IDC_COMBO_IC_BRIDGE             1003
#define IDC_BUTTON_VIEW_RIGHT           1004
#define IDC_EDIT2                       1004
#define IDC_EDIT_IC_ID                  1004
#define IDC_BUTTON_VIEW_FRONT           1005
#define IDC_MFCBUTTON1                  1005
#define IDC_MFCBUTTON_IC_STATUS         1005
#define IDC_BUTTON_VIEW_BACK            1006
#define IDC_MFCBUTTON_IC_INFO_MORE      1006
#define IDC_BUTTON_VIEW_UP              1007
#define IDC_STATIC_IC_I2C_CLOCK         1007
#define IDC_BUTTON_VIEW_DOWN            1008
#define IDC_STATIC_IC_ID                1008
#define IDC_STATIC_IC_I2C_ADDR          1009
#define IDC_STATIC_IC_BRIDGE            1010
#define IDC_MFCBUTTON_IC_INFO_MORE2     1011
#define IDC_MFCBUTTON_IC_INFO_STATUS    1011
#define IDR_PROPERTIES                  1125
#define IDB_PROPERTIES_HC               1126
#define ID_VIEW_PROPERTIESWND           1127
#define IDC_TEST_VIEW_TREE              1128
#define ID_Menu                         32776
#define ID_BUTTON_CON                   32777
#define ID_BUTTON_DISCON                32778
#define ID_BUTTON_IC                    32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_BUTTON32782                  32782
#define ID_BUTTON_TEST3                 32782
#define ID_BUTTON_TEST2                 32783
#define ID_BUTTON_TEST1                 32784
#define ID_SELECTALL_CLEAR              32785
#define ID_XLISTBOX_SELECTALL           32786
#define ID_XLISTBOX_COPY                32787
#define ID_XLISTBOX_CLEAR               32788
#define ID_32789                        32789
#define ID_VIEW_TEST_ITEM               32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_VIEW_PROPERTY                32794
#define ID_VIEW_OUTPUT                  32795
#define ID_VIEW_MACHINE                 32796
#define IDM_COLOR_RED                   32801
#define IDM_COLOR_GREEN                 32802
#define IDM_COLOR_BLACK                 32803
#define IDM_COLOR_YELLOW                32804
#define IDM_SHAPE_CIRCLE                32821
#define IDM_SHAPE_TRIANGLE              32822
#define IDM_SHAPE_SQUARE                32823
#define IDM_SHAPE_RED                   32824
#define IDM_SHAPE_YELLOW                32825
#define IDM_SHAPE_GREEN                 32826
#define IDM_SHAPE_CYAN                  32827
#define IDM_SHAPE_BLUE                  32828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        362
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
